name: CI/CD Build and Teams Notification

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install and Build Project
        run: |
          npm install -g @microsoft/teamsapp-cli
          teams -h
          npm install
          npm run build

      - name: Notify Teams on Success
        if: success()
        run: |
          teams message send --url ${{ secrets.TEAMS_WEBHOOK }} --message "✅ Build Successful for commit ${{ github.sha }} on branch ${{ github.ref_name }}"

      - name: Notify Teams on Failure
        if: failure()
        run: |
          teams message send --url ${{ secrets.TEAMS_WEBHOOK }} --message "❌ Build Failed for commit ${{ github.sha }} on branch ${{ github.ref_name }}"
