name: CI/CD Build and Teams Notification

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install and Build Project
        run: |
          npm install -g @microsoft/teamsapp-cli
          teamsapp -h
          npm install
          npm run build
          teamsapp package

      - name: Notify Teams on Success
        if: success()
        run: |
          curl -X POST ${{ secrets.TEAMS_WEBHOOK }} \
            -H 'Content-Type: application/json' \
            -d '{"text": "✅ Build Successful for commit '"${{ github.sha }}"' on branch '"${{ github.ref_name }}"' "}'

      - name: Notify Teams on Failure
        if: failure()
        run: |
          curl -X POST ${{ secrets.TEAMS_WEBHOOK }} \
            -H 'Content-Type: application/json' \
            -d '{"text": "❌ Build Failed for commit '"${{ github.sha }}"' on branch '"${{ github.ref_name }}"' "}'


